name: TECHcetera
favicon: null
layout_spectrum: 0.94239
typography_spectrum: 0.48839
title: TECHcetera
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#99cd68'
    - '#f15d59'
    - '#000000'
    - '#617598'
  brandStrength: 0.4375
  lightness: 0.5
  saturation: 0.5
  rhythmicContrast: 0.25
purpose: []
