name: TECHcetera
favicon: null
layout_spectrum: 0.94239
typography_spectrum: 0.8718583965674043
title: TECHcetera
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#99cd68'
    - '#f15d59'
    - '#000000'
    - '#617598'
  brandStrength: 0.6875
  lightness: 0.6024468801915646
  saturation: 0.4217789832036942
  rhythmicContrast: 0.75
purpose: []
